- type: job
  id: HeadOfSecurity
  name: job-name-hos
  description: job-description-hos
  playTimeTracker: JobHeadOfSecurity
  requirements:
    # Parkstation-Playtime
    - !type:CharacterPlaytimeRequirement
      tracker: JobWarden
      min: 14400 # 4 hours
    - !type:CharacterDepartmentTimeRequirement
      department: Security
      min: 21600 # 6 hours
    - !type:CharacterOverallTimeRequirement
      min: 93600 # 26 hours
    - !type:CharacterWhitelistRequirement
  weight: 10
  startingGear: HoSGear
  icon: "JobIconHeadOfSecurity"
  requireAdminNotify: true
  supervisors: job-supervisors-cc # ParkStation-Oligarchy
  canBeAntag: false
  access:
  - HeadOfSecurity
  - Command
  #- Brig  # Delta V: Removed
  - Security
  - Armory
  - Maintenance
  - Service
  - External
  - Detective
  - Corpsman # DeltaV - added Corpsman access
  - Cryogenics
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant ]
  - !type:AddComponentSpecial
    components:
      - type: CommandStaff

- type: startingGear
  id: HoSGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitHoS
    back: ClothingBackpackHOSFilled
    shoes: ClothingShoesBootsCombatFilled
    eyes: ClothingEyesGlassesSunglasses
    id: HoSPDA
    gloves: ClothingHandsGlovesCombat
    ears: ClothingHeadsetAltSecurity
    belt: ClothingBeltSecurityFilled
  innerClothingSkirt: ClothingUniformJumpskirtHoS
  satchel: ClothingBackpackSatchelHOSFilled
  duffelbag: ClothingBackpackDuffelHOSFilled
