- type: job
  id: HeadOfSecurity
  name: job-name-hos
  description: job-description-hos
  playTimeTracker: JobHeadOfSecurity
  requirements:
    # Parkstation-Playtime
    - !type:RoleTimeRequirement
      role: JobWarden
      time: 14400 # 4 hours
    - !type:DepartmentTimeRequirement
      department: Security
      time: 21600 # 6 hours
    - !type:OverallPlaytimeRequirement
      time: 93600 # 26 hours
    - !type:WhitelistRequirement # DeltaV - Whitelist requirement
  weight: 10
  startingGear: HoSGear
  icon: "JobIconHeadOfSecurity"
  requireAdminNotify: true
  supervisors: job-supervisors-captain
  canBeAntag: false
  access:
  - HeadOfSecurity
  - Command
  #- Brig  # Delta V: Removed
  - Security
  - Armory
  - Maintenance
  - Service
  - External
  - Detective
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant ]
  - !type:AddComponentSpecial
    components:
      - type: CommandStaff
  - !type:AddComponentSpecial
    components:
    - type: PsionicBonusChance #Nyano - Summary: makes it more likely to become psionic.
      flatBonus: 0.025

- type: startingGear
  id: HoSGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitHoS
    back: ClothingBackpackHOSFilled
    shoes: ClothingShoesBootsCombatFilled
    outerClothing: ClothingOuterCoatHoSTrench
    eyes: ClothingEyesGlassesSunglasses
    head: ClothingHeadHatBeretHoS
    id: HoSPDA
    gloves: ClothingHandsGlovesCombat
    ears: ClothingHeadsetAltSecurity
    belt: ClothingBeltSecurityFilled
    pocket1: WeaponPistolMk58Nonlethal
  innerClothingSkirt: ClothingUniformJumpskirtHoS
  satchel: ClothingBackpackSatchelHOSFilled
  duffelbag: ClothingBackpackDuffelHOSFilled
