- type: loadout
  id: LoadoutSecurityUniformGrey
  category: Jobs
  cost: 2
  exclusive: true
  requirements:
    - !type:LoadoutJobRequirement
      jobs:
        - SecurityOfficer
        - SecurityCadet
        - Warden
  items:
    - ClothingUniformJumpsuitSecGrey

- type: loadout
  id: LoadoutSecurityUniformJumpskirtSenior
  category: Jobs
  cost: 2
  exclusive: true
  requirements:
    - !type:LoadoutJobRequirement
      jobs:
        - SecurityOfficer
    - !type:LoadoutPlaytimeRequirement
      tracker: JobWarden
      min: 21600 # 6 hours
    - !type:LoadoutPlaytimeRequirement
      tracker: JobDetective
      min: 7200 # 2 hours
    - !type:LoadoutPlaytimeRequirement
      tracker: JobSecurityOfficer
      min: 21600 # 6 hours
    - !type:LoadoutDepartmentTimeRequirement
      department: Security
      min: 216000 # 60 hours
  items:
    - ClothingUniformJumpskirtSeniorOfficer

- type: loadout
  id: LoadoutSecurityUniformJumpsuitSenior
  category: Jobs
  cost: 2
  exclusive: true
  requirements:
    - !type:LoadoutJobRequirement
      jobs:
        - SecurityOfficer
    - !type:LoadoutPlaytimeRequirement
      tracker: JobWarden
      min: 21600 # 6 hours
    - !type:LoadoutPlaytimeRequirement
      tracker: JobDetective
      min: 7200 # 2 hours
    - !type:LoadoutPlaytimeRequirement
      tracker: JobSecurityOfficer
      min: 21600 # 6 hours
    - !type:LoadoutDepartmentTimeRequirement
      department: Security
      min: 216000 # 60 hours
  items:
    - ClothingUniformJumpsuitSeniorOfficer

- type: loadout
  id: LoadoutSecurityMaskGasSwat
  category: Jobs
  cost: 2
  exclusive: true
  requirements:
    - !type:LoadoutJobRequirement
      jobs:
        - Warden
        - HeadOfSecurity
  items:
    - ClothingMaskGasSwat

- type: loadout
  id: LoadoutSecurityShoesJackboots
  category: Jobs
  cost: 1
  requirements:
    - !type:LoadoutJobRequirement
      jobs:
        - Detective
        - SecurityOfficer
        - SecurityCadet
        - Warden
        - HeadOfSecurity
  items:
    - ClothingShoesBootsJack
