contact_links:
  - name: Report a Security Vulnerability
    url: https://github.com/space-wizards/space-station-14/blob/master/SECURITY.md
    about: Please report security vulnerabilities to the Space Wizards privately so they can fix them before they are publicly disclosed.
