- type: gameMapPool
  id: DefaultMapPool
  maps:
  #- Aspid
  #- Bagel
  #- Barratry
  #- Box
  #- Cluster
  #- Core
  #- Fland
  #- Kettle
  #- Marathon
  #- Meta
  #- Omega
  #- Origin
  #- Saltern
  #- Packed
# DeltaV
  #- Arena
  #- Asterisk
  #- Edge
  #- Hammurabi
  #- Pebble
  #- Shoukou
  #- Tortuga
  #- TheHive
# Parkstation
  - Dev # Until we get Arborum
