- type: job
  id: SalvageSpecialist
  name: job-name-salvagespec
  description: job-description-salvagespec
  playTimeTracker: JobSalvageSpecialist
  antagAdvantage: 3 # DeltaV - Reduced TC: External Access + Free hardsuit and weapons
  requirements:
    - !type:CharacterDepartmentTimeRequirement
      department: Engineering
      min: 21600 #DeltaV 6 hrs
  #  - !type:CharacterOverallTimeRequirement #DeltaV
  #    min: 36000 #10 hrs
  icon: "JobIconShaftMiner"
  startingGear: SalvageSpecialistGear
  supervisors: job-supervisors-ce # Parkstation-EngineeringSalvagers
  access:
  - Engineering # ParkStation-EngineeringSalvagers
  - Salvage
  - Maintenance
  - External

- type: startingGear
  id: SalvageSpecialistGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitSalvageSpecialist
    back: ClothingBackpackSalvageFilled
    shoes: ClothingShoesBootsSalvage
    id: SalvagePDA
    ears: ClothingHeadsetEngineering # Parkstation-EngineeringSalvagers
  satchel: ClothingBackpackSatchelSalvageFilled
  duffelbag: ClothingBackpackDuffelSalvageFilled
