- type: job
  id: ResearchDirector
  name: job-name-rd
  description: job-description-rd
  playTimeTracker: JobResearchDirector
  antagAdvantage: 6 # DeltaV - Reduced TC: Head of Staff
  requirements:
    # Parkstation-Playtime
    - !type:DepartmentTimeRequirement
      department: Epistemics
      time: 18000 # 5 hours
    - !type:OverallPlaytimeRequirement
      time: 86400 # 24 hours
  weight: 10
  startingGear: ResearchDirectorGear
  icon: "JobIconResearchDirector"
  requireAdminNotify: true
  supervisors: job-supervisors-captain
  canBeAntag: false
  access:
  - Research
  - Command
  - Maintenance
  - ResearchDirector
  - Mantis # DeltaV - Psionic Mantis, see Resources/Prototypes/DeltaV/Access/epistemics.yml
  - Chapel # DeltaV - Chaplain is in Epistemics
  special: # Nyanotrasen - Mystagogue can use the Bible
  - !type:AddComponentSpecial
    components:
    - type: BibleUser # Nyano - Lets them heal with bibles
    - type: Psionic # Nyano - They start with telepathic chat
    - type: DispelPower # Nyano - They get the Dispel psionic power on spawn
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant ]
  - !type:AddComponentSpecial
    components:
      - type: CommandStaff

- type: startingGear
  id: ResearchDirectorGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitResearchDirector
    back: ClothingBackpackResearchDirectorFilled
    shoes: ClothingShoesColorBrown
    head: ClothingHeadHoodMysta # DeltaV - Mystagogue new hat
    outerClothing: ClothingOuterCoatRndMysta # DeltaV - Mystagogue new coat
    id: RnDPDA
    ears: ClothingHeadsetRD
    belt: BibleMystagogue # Nyanotrasen - Mystagogue book for their Ifrit
  innerClothingSkirt: ClothingUniformJumpskirtResearchDirector
  satchel: ClothingBackpackSatchelResearchDirectorFilled
  duffelbag: ClothingBackpackDuffelResearchDirectorFilled
