- type: job
  id: ChiefServiceSupervisor
  name: job-name-css
  description: job-description-css
  playTimeTracker: JobChiefServiceSupervisor
  requirements:
    - !type:DepartmentTimeRequirement
      department: Civilian
      time: 21600
    - !type:OverallPlaytimeRequirement
      time: 86400
    - !type:WhitelistRequirement
  weight: 10
  startingGear: CSSGear
  icon: "JobIconCSS"
  requireAdminNotify: true
  supervisors: job-supervisors-cc
  canBeAntag: false
  antagAdvantage: 6
  access:
    - Command
    - ChiefServiceSupervisor
    - Bar
    - Service
    - Mail
    - Cargo
    - Maintenance
    - Janitor
    - Theatre
    - Kitchen
    - Hydroponics
  special:
    - !type:AddComponentSpecial
      components:
        - type: PsionicBonusChance
          flatBonus: 0.025

- type: startingGear
  id: CSSGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitCSS
    back: ClothingBackpackFilled
    outerClothing: ClothingOuterCoatCSS
    shoes: ClothingShoesBootsLaceup
    id: CSSPDA
    ears: ClothingHeadsetAltService
  innerClothingSkirt: ClothingUniformJumpskirtCSS
  satchel: ClothingBackpackSatchelFilled
  duffelbag: ClothingBackpackDuffelFilled
